# Generated by Django 3.2.9 on 2021-11-22 17:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('score', models.PositiveIntegerField()),
                ('shoots', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=7)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('D', 'Defender'), ('F', 'Forward')], default='F', max_length=7)),
                ('free_agent', models.BooleanField(default=False)),
                ('playing_for_national_team', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teams')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite_color', models.CharField(max_length=30)),
                ('favorite_music', models.CharField(max_length=30)),
                ('favorite_movie', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=30)),
                ('favorite_game', models.CharField(max_length=30)),
                ('favorite_car', models.CharField(max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legionary', models.BooleanField(default=False)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('captain', models.BooleanField(default=False)),
                ('salary_per_year', models.PositiveIntegerField()),
                ('sport_brand', models.CharField(choices=[('CCM', 'CCM'), ('Under Armour', 'Under Armour'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok'), ('New Balance', 'New Balance'), ('Bauer', 'Bauer'), ('Easton', 'Easton')], max_length=15)),
                ('contract_till', models.DateField()),
                ('academy', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
    ]
