//teams
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_PARTICULAR_TEAM = 'GET_PARTICULAR_TEAM';
//players
export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_PARTICULAR_PLAYER = 'GET_PARTICULAR_PLAYER';
//leagues
export const GET_ALL_LEAGUES = 'GET_ALL_LEAGUES';
export const GET_PARTICULAR_LEAGUE = 'GET_PARTICULAR_LEAGUE';
//stadiums
export const GET_ALL_STADIUMS = 'GET_ALL_STADIUMS';
export const GET_PARTICULAR_STADIUM = 'GET_PARTICULAR_STADIUM';
//news
export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const GET_PARTICULAR_NEWS = 'GET_PARTICULAR_NEWS';
//comments
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_PARTICULAR_COMMENT = 'GET_PARTICULAR_COMMENT';

//users
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_PARTICULAR_USER = 'GET_PARTICULAR_USER';



//colors
export const MAKE_RED = 'MAKE_RED';
export const MAKE_BLUE = 'MAKE_BLUE';