# Generated by Django 3.2.9 on 2021-11-27 15:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('league_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('history', models.TextField()),
                ('description', models.TextField()),
                ('founders', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
