# Generated by Django 3.2.9 on 2021-12-04 06:52

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_just'),
        ('leagues', '0002_alter_league_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='general.city'),
        ),
    ]
