# Generated by Django 3.2.8 on 2021-12-15 11:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_league_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
