# Generated by Django 3.2.8 on 2021-12-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_league_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
