# Generated by Django 3.2.8 on 2021-12-21 09:54

import apps.leagues.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.leagues.models.models.get_upload_to_leagues),
        ),
    ]
