# Generated by Django 3.2.8 on 2021-12-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_league_league_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='city',
        ),
    ]
