# Generated by Django 3.2.8 on 2021-12-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_remove_league_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Leagues', 'verbose_name_plural': 'Leagues'},
        ),
    ]
