# Generated by Django 3.2.7 on 2021-11-25 15:59

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('history', models.TextField()),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('budget', models.PositiveIntegerField()),
                ('fanbase', models.PositiveIntegerField()),
                ('sponsors', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('sport_brand', models.CharField(choices=[('CCM', 'CCM'), ('Under Armour', 'Under Armour'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok'), ('New Balance', 'New Balance'), ('Bauer', 'Bauer'), ('Easton', 'Easton')], max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.leagues')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField()),
                ('avg_attendence', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rebuild', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teams')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='teams.teams')),
                ('t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='teams.teams')),
            ],
        ),
    ]
