# Generated by Django 3.2.7 on 2021-11-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wins',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='teams.team'), max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.PositiveIntegerField()),
                ('goals_missed', models.PositiveIntegerField()),
                ('matches', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
