# Generated by Django 3.2.7 on 2021-12-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20211204_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_OT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_OT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
