# Generated by Django 3.2.8 on 2021-12-15 11:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20211208_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
