# Generated by Django 3.2.8 on 2021-12-17 07:57

import apps.teams.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20211215_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_background',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teams.models.models.get_upload_to_teams),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teams.models.models.get_upload_to_teams),
        ),
    ]
