# Generated by Django 3.2.8 on 2021-12-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20211217_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sum_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
