# Generated by Django 3.2.8 on 2021-12-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_sum_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sum_points',
        ),
    ]
