# Generated by Django 3.2.8 on 2021-12-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_sum_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='win',
        ),
    ]
