# Generated by Django 3.2.8 on 2021-12-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20211224_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
    ]
