# Generated by Django 3.2.8 on 2021-12-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20211224_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'verbose_name': 'Stadium', 'verbose_name_plural': 'Stadiums'},
        ),
    ]
