# Generated by Django 3.2.8 on 2021-12-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20211224_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AddField(
            model_name='game',
            name='lucky',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='lucky_overtime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='lucky_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
