# Generated by Django 3.2.9 on 2021-12-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_just'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Just',
        ),
    ]
