# Generated by Django 3.2.9 on 2021-12-05 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20211204_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 14, 53, 37, 473783)),
        ),
    ]
