# Generated by Django 3.2.9 on 2021-12-05 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_city_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='d',
        ),
        migrations.AddField(
            model_name='just2',
            name='dd',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
