# Generated by Django 3.2.9 on 2021-12-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20211205_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='just2',
            name='dd',
        ),
    ]
