# Generated by Django 3.2.8 on 2021-12-09 17:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_remove_just2_dd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='general.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
            ],
            options={
                'verbose_name': 'Fun Club',
                'verbose_name_plural': 'Fun Clubs',
            },
        ),
    ]
