# Generated by Django 3.2.8 on 2021-12-15 11:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_funclubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='just2',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
