# Generated by Django 3.2.8 on 2021-12-15 11:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_just2_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='just2',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
