# Generated by Django 3.2.8 on 2021-12-15 11:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_alter_just2_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='funclubs',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
