# Generated by Django 3.2.8 on 2021-12-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20211215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='just2',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country'),
        ),
    ]
