# Generated by Django 3.2.8 on 2021-12-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20211215_1504'),
        ('general', '0014_alter_just2_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='just2',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
    ]
