# Generated by Django 3.2.8 on 2021-12-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_city22'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='just2',
            name='country',
        ),
        migrations.DeleteModel(
            name='City22',
        ),
        migrations.DeleteModel(
            name='Country22',
        ),
    ]
