# Generated by Django 3.2.8 on 2021-12-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_country'),
        ('general', '0018_auto_20211215_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
