# Generated by Django 3.2.8 on 2021-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='just2',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
