# Generated by Django 3.2.8 on 2021-12-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20211224_0752'),
        ('users', '0005_remove_userprofile_city'),
        ('leagues', '0007_remove_league_city'),
        ('players', '0012_remove_player_city'),
        ('general', '0020_just2_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funclubs',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
