# Generated by Django 3.2.8 on 2021-12-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20211224_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Just2',
        ),
    ]
