# Generated by Django 3.2.8 on 2021-12-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_delete_just2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunClubs',
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
