# Generated by Django 3.2.8 on 2021-12-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_headtohead'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
