# Generated by Django 3.2.8 on 2021-12-15 11:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
