# Generated by Django 3.2.8 on 2021-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_number',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
