# Generated by Django 3.2.8 on 2021-12-21 09:16

import apps.players.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.players.models.models.get_upload_to_players),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.players.models.models.get_upload_to_players),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Forward', 'Forward')], default='Forward', max_length=10),
        ),
    ]
