# Generated by Django 3.2.8 on 2021-12-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20211221_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalie', 'Goalie'), ('Defender', 'Defender'), ('Forward', 'Forward')], default='Forward', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='shoots',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=10),
        ),
    ]
