# Generated by Django 3.2.8 on 2021-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20211221_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermaininfo',
            name='captain',
        ),
        migrations.AddField(
            model_name='player',
            name='captain',
            field=models.BooleanField(default=False),
        ),
    ]
