# Generated by Django 3.2.8 on 2021-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20211221_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='second_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
