# Generated by Django 3.2.7 on 2021-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
