# Generated by Django 3.2.8 on 2021-12-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211227_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspecialfields',
            name='ban',
        ),
    ]
