# Generated by Django 3.2.8 on 2021-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userspecialfields_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecialfields',
            name='is_moderator',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
