# Generated by Django 3.2.9 on 2021-11-22 17:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('coat_of_arms', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('populations', models.IntegerField()),
                ('still_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('coat_of_arms', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('populations', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
